#function loadlib() {
#  lib=$1 #:?"You have to specify a library file"}
  #if [ -f "$lib" ] ;then #ファイルの存在を確認
#  source "$lib"
  #fi
#}

ZDIR="${HOME}/Dropbox/dotfiles/zsh_conf"

#source $ZDIR/zshvars        #変数
#source $ZDIR/zfunc        #関数
. ${ZDIR}/zhistory    #history
. ${ZDIR}/zalias       #alias
. ${ZDIR}/zcolor      # 色
. ${ZDIR}/zset        #setoptとかzstyleとか
. ${ZDIR}/zplugin     # 各種プラグイン
. ${ZDIR}/zprompt     #prompt 最後に読むのが吉？
